### ISSUE TITLE
Test moco with elbow model

### ISSUE THREAD

**Issue by dblana** [dblana/TechForParalysis#12]
- [ ] Successfully run all examples that come with moco
- [ ] Set up moco to run with simple elbow model
- [ ] Run optimisation 1: prescribe elbow angle 
- [ ] Run optimisation 2: track elbow angle in the cost function 
- [ ] Run optimisation 3: specify only start and end angle and the duration of movement

**Comment by dblana** [comment]
Hi @RostiReadioff, I thought I'd make an issue so we can keep track of progress (and any problems) - feel free to suggest changes to the above list, it's just an initial idea 😄

**Comment by RostiReadioff** [comment]
@dblana, thanks that's excellent.

**Comment by dblana** [comment]
I'm closing this as the current plan is to use our implicit formulation instead of Moco
