### ISSUE TITLE
Increase optimality and feasibility tolerances of last iteration

### ISSUE THREAD

**Issue by dblana** [dblana/TechForParalysis#7]
This is for runopt_elbow.m (lines 36 & 37)

**Comment by RostiReadioff** [comment]
I have changed the tolerance values on line 36&37 from 1e-5 to 1e-3 for both. In addition, I reduced max node number from 40 to 20. The optimisation run successfully and the simulation found optimal solutions.

**Comment by dblana** [comment]
Great, do you want to do a pull request so we can marge those changes into the master branch?

**Comment by RostiReadioff** [comment]
Pull request created. It is ready to be merged or declined. I also have the right to accept the pull request, but I leave that for you to manage.

**Comment by dblana** [comment]
Well done! :tada: I've left a comment about removing the opt_results folder, since these data files can be easily generated and there is no need to keep them under version control.

**Comment by RostiReadioff** [comment]
Not sure what the next step is, so I leave it as is for now and we can discuss next time we meet.
